const schedule = {
  monday:[
    {time:'08:50–10:20',name:'Техническое черчение',detail:'Доц. Трубецкая О.В.; Доц. Коршунов Д.А.',room:'пр. №722 / №721'},
    {time:'10:35–12:05',name:'История России',detail:'Доц. Мокеев А.Б.',room:'№633'},
    {time:'12:35–14:05',name:'Высшая математика',detail:'Асс. Смирнова Е.А.',room:'пр. №523'}
  ],
  tuesday:[
    {time:'10:35–12:05',name:'Физическая культура и спорт',detail:'Обязательная факультативная дисциплина',room:''},
    {time:'12:35–14:05',name:'Основы экономики',detail:'Доц. Никифоров А.А.',room:'пр. №622'},
    {time:'14:15–15:45',name:'Концепции современного естествознания',detail:'Доц. Вологин Е.А.',room:'I · пр. №539'},
    {time:'14:15–15:45',name:'Риторика и деловой этикет',detail:'Доц. Бойко Ж.В.',room:'II · пр. №539'},
    {time:'15:55–17:20',name:'Риторика и деловой этикет',detail:'Доц. Бондарева О.Н.',room:'I · №326'},
    {time:'15:55–17:20',name:'Концепции современного естествознания',detail:'Проф. Бричкин В.Н.',room:'II · №326'}
  ],
  wednesday:[
    {time:'08:50–10:20',name:'Введение в информационные технологии',detail:'Доц. Кротова С.Ю.; Асс. Лелен Алекса',room:'I · пр. №643 / №646'},
    {time:'08:50–10:20',name:'Техническое черчение',detail:'Доц. Коршунов Д.А.; Доц. Трубецкая О.В.',room:'II · пр. №823 / №724'},
    {time:'10:35–12:05',name:'Иностранный язык',detail:'Преподаватели не указаны',room:'пр. №834 / №830'},
    {time:'12:35–14:05',name:'Основы российской государственности',detail:'Доц. Вахнин Н.А.',room:'I · №824'},
    {time:'12:35–14:05',name:'Введение в информационные технологии',detail:'Доц. Овчинникова Е.Н.',room:'II · №333'},
    {time:'14:15–15:45',name:'Техническое черчение',detail:'Доц. Коршунов Д.А.',room:'I · №333'},
    {time:'14:15–15:45',name:'Основы российской государственности',detail:'Доц. Козлов О.В.',room:'II · пр. №717'}
  ],
  thursday:[
    {time:'08:50–10:20',name:'Введение в информационные технологии',detail:'Доц. Кротова С.Ю.; Асс. Лелен Алекса',room:'пр. №515 / №719'},
    {time:'10:35–12:05',name:'Основы экономики',detail:'Доц. Никифоров А.А.',room:'№624'},
    {time:'12:35–14:05',name:'История России',detail:'Доц. Лейберов А.И.',room:'пр. №639'}
  ],
  friday:[
    {time:'12:35–14:05',name:'Высшая математика',detail:'Проф. Дорофеев А.В.',room:'№536'},
    {time:'14:15–15:45',name:'Введение в специальность',detail:'Доц. Ковальский Е.Р.',room:'№403'}
  ]
};
const mySchedule=JSON.parse(JSON.stringify(schedule));
const friendSchedule={
  monday:[
    {time:'12:35–14:05',name:'Основы организации и управления производством',detail:'Ст. пр. Лебедев А.П.',room:'I · №4516'},
    {time:'12:35–14:05',name:'Процессы и аппараты химической технологии',detail:'Доц. Назаренко М.Ю.',room:'II · №3430'},
    {time:'14:15–15:45',name:'Процессы и аппараты химической технологии',detail:'Доц. Георгиева Э.Ю.',room:'I · №6303'},
    {time:'14:15–15:45',name:'Экономика отрасли',detail:'Доц. Туровская Л.Г.',room:'II · №6303'},
    {time:'15:55–17:20',name:'Отраслевое право',detail:'Доц. Батова О.В.',room:'I · №3219'},
    {time:'15:55–17:20',name:'Физическая и коллоидная химия',detail:'Проф. Черемисина О.В.',room:'II · №4312'}
  ],
  tuesday:[
    {time:'08:50–10:20',name:'Основы теории и практики автоматизации',detail:'Доц. Петров П.А.',room:'№4312'},
    {time:'10:35–12:05',name:'Физическая и коллоидная химия',detail:'Проф. Литвинова Т.Е.',room:'I · №6306'},
    {time:'10:35–12:05',name:'Основы организации и управления производством',detail:'Ст. пр. Лебедев А.П.',room:'II · №6306'},
    {time:'12:35–14:05',name:'Процессы и аппараты химической технологии',detail:'Доц. Георгиева Э.Ю.',room:'II · №3430'}
  ],
  wednesday:[
    {time:'12:35–14:05',name:'Процессы и аппараты химической технологии',detail:'Доц. Назаренко М.Ю.',room:'№3430'},
    {time:'14:15–15:45',name:'Физическая и коллоидная химия',detail:'Проф. Литвинова Т.Е.',room:'№4312'},
    {time:'15:55–17:20',name:'Основы организации и управления производством',detail:'Доц. Васильев Ю.Н.',room:'№3531'}
  ],
  thursday:[
    {time:'08:50–10:20',name:'Экономика отрасли',detail:'Доц. Столбовская Н.В.',room:'№3531'},
    {time:'10:35–12:05',name:'Основы теории и практики автоматизации',detail:'Доц. Романова Н.А.',room:'пр. №7310',slot:'1/2'},
    {time:'10:35–12:05',name:'Процессы и аппараты химической технологии',detail:'Доц. Георгиева Э.Ю.',room:'пр. №3430',slot:'1/2'},
    {time:'12:35–14:05',name:'Отраслевое право',detail:'Доц. Батова О.В.',room:'I · пр. №4516'},
    {time:'12:35–14:05',name:'Физическая и коллоидная химия',detail:'Проф. Литвинова Т.Е.',room:'II · пр. №4516'},
    {time:'14:15–15:45',name:'Физическая культура и спорт',detail:'Обязательная факультативная дисциплина',room:''}
  ],
  friday:[
    {time:'08:50–10:20',name:'Процессы и аппараты химической технологии',detail:'Доц. Георгиева Э.Ю.',room:'№6306'},
    {time:'10:35–12:05',name:'Экономика отрасли',detail:'Доц. Туровская Л.Г.',room:'I · пр. №6306'},
    {time:'10:35–12:05',name:'Физическая и коллоидная химия',detail:'Асс. Минина А.А.',room:'II · пр. №6306'},
    {time:'12:35–14:05',name:'Основы теории и практики автоматизации',detail:'Доц. Романова Н.А.',room:'пр. №7218'}
  ]
};
const profiles={vlad:{name:'Влад',label:'Студент',group:'ТГР-26-1',schedule:mySchedule},ignatiy:{name:'Игнатий',label:'Студент',group:'ТХН-23',schedule:friendSchedule}};
let activeProfile=localStorage.getItem('diaryProfile')||'vlad';
function applyProfile(key){activeProfile=profiles[key]?key:'vlad';localStorage.setItem('diaryProfile',activeProfile);dayKeys.filter(k=>k!=='sunday'&&k!=='saturday').forEach(k=>{schedule[k]=JSON.parse(JSON.stringify(profiles[activeProfile].schedule[k]||[]))})}
const dayNames={sunday:'Воскресенье',monday:'Понедельник',tuesday:'Вторник',wednesday:'Среда',thursday:'Четверг',friday:'Пятница',saturday:'Суббота'};
const dayShort={sunday:'ВС',monday:'ПН',tuesday:'ВТ',wednesday:'СР',thursday:'ЧТ',friday:'ПТ',saturday:'СБ'};
const dayKeys=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
const currentDate=new Date();
const todayKey=dayKeys[currentDate.getDay()];
const currentDateLabel=currentDate.toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
setTimeout(()=>window.location.reload(),Math.max(1000,new Date(currentDate.getFullYear(),currentDate.getMonth(),currentDate.getDate()+1).getTime()-Date.now()+1000));
applyProfile(activeProfile);
function weekMonday(date){const d=new Date(date);const day=d.getDay();d.setHours(0,0,0,0);d.setDate(d.getDate()+(day===0?-6:1-day));return d}
function weekType(date){const anchor=weekMonday(new Date(2026,8,7));const current=weekMonday(date);const weeks=Math.round((current-anchor)/604800000);return ((weeks%2)+2)%2===0?'II':'I'}
function weekRangeLabel(date){const start=weekMonday(date);const end=new Date(start);end.setDate(start.getDate()+6);return `${start.getDate()}–${end.getDate()} ${end.toLocaleDateString('ru-RU',{month:'long',year:'numeric'})}`}
const defaultTasks=[{title:'Подготовить конспект по истории России',subject:'История России',due:'Сегодня',priority:'Высокий',done:false},{title:'Прочитать главу по естествознанию',subject:'Концепции современного естествознания',due:'Завтра',priority:'Средний',done:false},{title:'Сдать практическую работу',subject:'Техническое черчение',due:'12 сентября',priority:'Высокий',done:false}];
let tasks=JSON.parse(localStorage.getItem('diaryTasks')||'null')||defaultTasks;
let grades=JSON.parse(localStorage.getItem('diaryGrades')||'null')||[{subject:'История России',type:'Семинар',date:'04.09.2026',value:5},{subject:'Высшая математика',type:'Контрольная',date:'03.09.2026',value:4},{subject:'Введение в специальность',type:'Зачёт',date:'01.09.2026',value:5}];
let debts=JSON.parse(localStorage.getItem('diaryDebts')||'null')||[{subject:'Техническое черчение',reason:'Не сдана практическая работа',due:'18 сентября',status:'Срочно'},{subject:'Физическая культура и спорт',reason:'Не закрыта ведомость',due:'Не указан',status:'В работе'}];
function saveGrades(){localStorage.setItem('diaryGrades',JSON.stringify(grades))}function saveDebts(){localStorage.setItem('diaryDebts',JSON.stringify(debts))}
let view='dashboard'; let selectedDay=todayKey; let selectedWeek=weekType(currentDate);
const appView=document.getElementById('appView');
const weekSwitchObserver=new MutationObserver(()=>document.querySelectorAll('.week-switch button').forEach(b=>{if(!b.dataset.week){b.dataset.week=b.textContent.trim();b.addEventListener('click',()=>{selectedWeek=b.dataset.week;render()})}b.classList.toggle('active',b.textContent.trim()===selectedWeek)}));weekSwitchObserver.observe(appView,{childList:true,subtree:true});
function save(){localStorage.setItem('diaryTasks',JSON.stringify(tasks));}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function lessonMarkup(items,compact=false,week=null){items=items||[];const visible=week?items.filter(x=>!x.room||!/^(I|II) ·/.test(x.room)||x.room.startsWith(`${week} ·`)):items;if(!visible.length)return '<div class="empty">Занятий нет — можно добавить личное событие</div>';return `<div class="lesson-list">${visible.map((x,i)=>`<div class="${compact?'lesson':'schedule-entry'}"><div class="${compact?'lesson-time':'schedule-time'}">${x.time}</div><div><div class="${compact?'lesson-name':'schedule-name'}">${x.name}</div><div class="${compact?'lesson-meta':'schedule-detail'}">${x.detail}</div></div>${x.room?`<div class="lesson-room">${x.room}</div>`:''}</div>`).join('')}</div>`}
function taskMarkup(){return `<div class="task-list">${tasks.map((t,i)=>`<div class="task-row ${t.done?'done':''}"><button class="check" data-task="${i}" aria-label="Отметить выполнение">${t.done?'✓':''}</button><div><div class="task-name">${t.title}</div><div class="task-meta"><span class="tag">${t.subject}</span><span class="tag ${t.priority==='Высокий'?'danger':'warn'}">${t.priority}</span><span>${t.due}</span></div></div></div>`).join('')}</div>`}
function dashboard(){return `<div class="metric-grid"><div class="metric"><span class="metric-label">Средний балл</span><span class="metric-value">4,5</span><span class="metric-note">↑ 0,3 за месяц</span></div><div class="metric"><span class="metric-label">Заданий на неделе</span><span class="metric-value">${tasks.filter(t=>!t.done).length}</span><span class="metric-note">2 с высоким приоритетом</span></div><div class="metric"><span class="metric-label">Учебные долги</span><span class="metric-value">2</span><span class="metric-note" style="color:var(--red)">Требуют внимания</span></div></div><div class="page-grid"><div class="section-stack"><section class="card today-card"><div class="card-header"><div><h2 class="card-title">Сегодня · ${dayNames[todayKey]}, ${currentDateLabel}</h2><p class="card-subtitle">Текущая неделя ${selectedWeek}</p></div><button class="link-button" data-view-link="schedule">Всё расписание →</button></div>${lessonMarkup(schedule[todayKey]||[],true,selectedWeek)}</section><section class="card"><div class="card-header"><div><h2 class="card-title">Ближайшие задания</h2><p class="card-subtitle">Не упусти важное</p></div><button class="link-button" data-view-link="tasks">Все задания →</button></div>${taskMarkup()}</section></div><div class="section-stack"><section class="card"><div class="card-header"><div><h2 class="card-title">Текущая неделя · ${selectedWeek}</h2><p class="card-subtitle">${weekRangeLabel(currentDate)}</p></div><div class="week-switch"><button> I </button><button class="active">II</button></div></div><div style="font-size:13px;line-height:1.6;color:var(--muted)">Сегодня — ${dayNames[todayKey].toLowerCase()}, ${currentDateLabel}.</div></section><section class="card"><div class="card-header"><div><h2 class="card-title">Быстрые действия</h2><p class="card-subtitle">Добавить за пару секунд</p></div></div><div class="quick-actions"><button class="outline-button quick-action" data-action="task">＋ Задание</button><button class="outline-button quick-action" data-action="grade">＋ Оценку</button><button class="outline-button quick-action" data-action="debt">＋ Долг</button></div></section></div></div>`}
function scheduleView(){return `<div class="view-toolbar"><div><h2 class="view-title">Расписание</h2><p class="card-subtitle">Группа ТГР-26-1 · осенний семестр 2026–2027</p></div><div class="week-switch"><button class="${selectedWeek==='I'?'active':''}" data-week="I">Неделя I</button><button class="${selectedWeek==='II'?'active':''}" data-week="II">Неделя II</button></div></div><section class="card"><div class="day-tabs">${Object.keys(dayNames).filter(k=>k!=='sunday'&&k!=='saturday').map(k=>`<button class="day-tab ${selectedDay===k?'active':''}" data-day="${k}"><strong>${dayShort[k]}</strong><small>${dayNames[k]}</small></button>`).join('')}</div><div style="margin-top:20px"><h3 class="card-title">${dayNames[selectedDay]}</h3><p class="card-subtitle">Тип недели: ${selectedWeek} · ${currentDateLabel}</p><div style="margin-top:8px">${lessonMarkup(schedule[selectedDay]||[],false,selectedWeek)}</div></div></section>`}
function tasksView(){return `<div class="view-toolbar"><div><h2 class="view-title">Задания</h2><p class="card-subtitle">${tasks.filter(t=>!t.done).length} активных задания</p></div><button class="primary-button" data-action="task">＋ Добавить задание</button></div><section class="card">${taskMarkup()}</section>`}
function gradesView(){return `<div class="view-toolbar"><div><h2 class="view-title">Оценки</h2><p class="card-subtitle">Успеваемость по предметам</p></div><button class="primary-button" data-action="grade">＋ Добавить оценку</button></div><section class="card"><table class="table"><thead><tr><th>Предмет</th><th>Тип</th><th>Дата</th><th>Оценка</th></tr></thead><tbody><tr><td>История России</td><td>Семинар</td><td>04.09.2026</td><td><span class="grade-pill">5</span></td></tr><tr><td>Высшая математика</td><td>Контрольная</td><td>03.09.2026</td><td><span class="grade-pill">4</span></td></tr><tr><td>Введение в специальность</td><td>Зачёт</td><td>01.09.2026</td><td><span class="grade-pill">5</span></td></tr></tbody></table></section>`}
function debtsView(){return `<div class="view-toolbar"><div><h2 class="view-title">Учебные долги</h2><p class="card-subtitle">Две записи требуют внимания</p></div><button class="primary-button" data-action="debt">＋ Добавить долг</button></div><section class="card"><div class="debt-list"><div class="task-row"><span class="tag danger">Срочно</span><div><div class="task-name">Техническое черчение</div><div class="task-meta"><span>Не сдана практическая работа</span><span>Пересдача: 18 сентября</span></div></div></div><div class="task-row"><span class="tag warn">В работе</span><div><div class="task-name">Физическая культура и спорт</div><div class="task-meta"><span>Не закрыта ведомость</span><span>Преподаватель не указан</span></div></div></div></div></section>`}
function calendarView(){const keys=['monday','tuesday','wednesday','thursday','friday',null,null];const start=weekMonday(currentDate);const dates=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d});const eventMarkup=(key)=>{if(!key)return '<div class="calendar-empty">Выходной</div>';const items=(schedule[key]||[]).filter(x=>!x.room||!/^(I|II) ·/.test(x.room)||x.room.startsWith(`${selectedWeek} ·`));if(!items.length)return '<div class="calendar-empty">Нет занятий</div>';return `<div class="calendar-events">${items.map(x=>`<div class="calendar-event"><span>${x.time}</span><b>${x.name}</b>${x.room?`<small>${x.room}</small>`:''}</div>`).join('')}</div>`};return `<div class="view-toolbar"><div><h2 class="view-title">Календарь недели</h2><p class="card-subtitle">${weekRangeLabel(currentDate)} · текущая неделя ${selectedWeek}</p></div><button class="primary-button">Сегодня · ${dayShort[todayKey]}, ${currentDateLabel}</button></div><section class="card"><div class="calendar-grid">${dates.map((date,i)=>`<div class="calendar-head">${dayShort[keys[i]||dayKeys[date.getDay()]||'sunday']}</div>`).join('')}${dates.map((date,i)=>{const key=keys[i];const isToday=date.toDateString()===currentDate.toDateString();return `<div class="calendar-day ${isToday?'today':''}"><div class="calendar-date"><strong>${date.getDate()}</strong><span>${key?dayNames[key]:''}</span></div>${eventMarkup(key)}</div>`}).join('')}</div></section>`}
function render(){const views={dashboard:dashboard,schedule:scheduleView,calendar:calendarView,tasks:tasksView,grades:gradesView,debts:debtsView};appView.innerHTML=views[view]();document.getElementById('dateLabel').textContent=`${dayNames[todayKey]}, ${currentDateLabel}`;document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('pageTitle').textContent=view==='dashboard'?'Доброе утро, Влад':({schedule:'Расписание',calendar:'Календарь',tasks:'Задания',grades:'Оценки',debts:'Учебные долги'}[view]);document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render()}));document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.viewLink;render()}));document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>{selectedDay=b.dataset.day;render()}));document.querySelectorAll('[data-week]').forEach(b=>b.addEventListener('click',()=>{selectedWeek=b.dataset.week;render()}));document.querySelectorAll('[data-task]').forEach(b=>b.addEventListener('click',()=>{tasks[b.dataset.task].done=!tasks[b.dataset.task].done;save();render();toast('Статус задания обновлён')}));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>quickAction(b.dataset.action)));document.getElementById('taskBadge').textContent=tasks.filter(t=>!t.done).length}
function quickAction(type){if(type==='task'){const title=prompt('Название задания');if(title){tasks.push({title,subject:'Общее',due:'Без срока',priority:'Средний',done:false});save();render();toast('Задание добавлено')}}else if(type==='grade'){toast('Форма оценок будет добавлена следующим шагом')}else{toast('Форма долгов будет добавлена следующим шагом')}}
function syncProfileUi(){const profile=profiles[activeProfile];document.getElementById('profileName').textContent=profile.name;document.getElementById('profileGroup').textContent=profile.group;document.getElementById('profileAvatar').textContent=profile.name==='Игнатий'?'И':'ВП';document.getElementById('profileSelect').value=activeProfile;document.getElementById('pageTitle').textContent=view==='dashboard'?`Доброе утро, ${profile.name}`:({schedule:'Расписание',calendar:'Календарь',tasks:'Задания',grades:'Оценки',debts:'Учебные долги'}[view]);const scheduleSubtitle=[...document.querySelectorAll('.card-subtitle')].find(el=>el.textContent.includes('Группа ТГР-26-1'));if(scheduleSubtitle)scheduleSubtitle.textContent=`Группа ${profile.group} · осенний семестр 2026–2027`}
document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render();syncProfileUi()}));document.getElementById('quickAdd').addEventListener('click',()=>quickAction('task'));document.getElementById('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');toast('Тема переключена')});document.getElementById('profileSelect').addEventListener('change',e=>{applyProfile(e.target.value);selectedDay=todayKey;selectedWeek=weekType(currentDate);render();syncProfileUi();toast(`Профиль ${profiles[activeProfile].name} выбран`)});
document.querySelector('.bottom-nav').innerHTML=[['dashboard','⌂','Главная'],['schedule','▦','Расписание'],['calendar','◷','Календарь'],['tasks','✓','Задания'],['grades','★','Оценки'],['debts','!','Долги']].map(x=>`<button class="nav-item ${x[0]==='dashboard'?'active':''}" data-view="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('');
render();
syncProfileUi();
document.querySelectorAll('.week-switch button').forEach(b=>{if(!b.dataset.week)b.classList.toggle('active',b.textContent.trim()===selectedWeek)});
function lessonMarkup(items,compact=false,week=null){items=items||[];const visible=week?items.filter(x=>!x.room||!/^(I|II) ·/.test(x.room)||x.room.startsWith(`${week} ·`)):items;if(!visible.length)return '<div class="empty">Занятий нет — можно добавить личное событие</div>';const groups=[];visible.forEach(item=>{let group=groups.find(x=>x.time===item.time);if(!group){group={time:item.time,items:[]};groups.push(group)}group.items.push(item)});const roomOf=x=>x.room?x.room.replace(/^(I|II) ·\s*/,''):'';const labelOf=x=>x.slot||((x.room||'').match(/^(I|II) ·/)||[])[1]||'';return `<div class="lesson-list">${groups.map(group=>{const multi=group.items.length>1;return `<div class="${compact?'lesson':'schedule-entry'}"><div class="${compact?'lesson-time':'schedule-time'}">${group.time}</div><div>${group.items.map(x=>`<div class="lesson-part">${multi||labelOf(x)?`<span class="lesson-week">${labelOf(x)}</span>`:''}<div class="${compact?'lesson-name':'schedule-name'}">${x.name}</div><div class="${compact?'lesson-meta':'schedule-detail'}">${x.detail}</div>${multi?(roomOf(x)?`<div class="lesson-room">${roomOf(x)}</div>`:''):''}</div>`).join('')}</div>${!multi&&roomOf(group.items[0])?`<div class="lesson-room">${roomOf(group.items[0])}</div>`:''}</div>`}).join('')}</div>`}
function lessonMarkup(items,compact=false,week=null){items=items||[];const visible=week?items.filter(x=>!x.room||!/^(I|II) ·/.test(x.room)||x.room.startsWith(`${week} ·`)):items;if(!visible.length)return '<div class="empty">Занятий нет — можно добавить личное событие</div>';const groups=[];visible.forEach(item=>{let group=groups.find(x=>x.time===item.time);if(!group){group={time:item.time,items:[]};groups.push(group)}group.items.push(item)});const roomOf=x=>x.room?x.room.replace(/^(I|II) ·\s*/,''):'';const labelOf=x=>x.slot||((x.room||'').match(/^(I|II) ·/)||[])[1]||'';return `<div class="lesson-list">${groups.map(group=>{const multi=group.items.length>1;return `<div class="${compact?'lesson':'schedule-entry'}"><div class="${compact?'lesson-time':'schedule-time'}">${group.time}</div><div>${group.items.map(x=>`<div class="lesson-part">${multi||labelOf(x)?`<span class="lesson-week">${labelOf(x)}</span>`:''}<div class="${compact?'lesson-name':'schedule-name'}">${x.name}</div><div class="${compact?'lesson-meta':'schedule-detail'}">${x.detail}</div>${multi?'':(roomOf(x)?`<div class="lesson-room">${roomOf(x)}</div>`:'')}</div>`).join('')}</div>${multi?'':(roomOf(group.items[0])?`<div class="lesson-room">${roomOf(group.items[0])}</div>`:'')}</div>`}).join('')}</div>`}
document.getElementById('profileSwitch').addEventListener('click',()=>document.getElementById('profileMenu').classList.toggle('open'));document.querySelectorAll('[data-profile]').forEach(b=>b.addEventListener('click',()=>{applyProfile(b.dataset.profile);selectedDay=todayKey;selectedWeek=weekType(currentDate);document.getElementById('profileMenu').classList.remove('open');render();syncProfileUi();toast(`Профиль ${profiles[activeProfile].name} выбран`)}));
function taskMarkup(){return `<div class="task-list">${tasks.map((t,i)=>`<div class="task-row ${t.done?'done':''}"><button class="check" data-task="${i}" aria-label="Отметить выполнение">${t.done?'✓':''}</button><div class="item-main"><div class="task-name">${t.title}</div><div class="task-meta"><span class="tag">${t.subject}</span><span class="tag ${t.priority==='Высокий'?'danger':'warn'}">${t.priority}</span><span>${t.due}</span></div></div><div class="item-actions"><button class="item-action" data-edit-task="${i}" aria-label="Изменить задание">Изменить</button><button class="item-action danger-action" data-delete-task="${i}" aria-label="Удалить задание">Удалить</button></div></div>`).join('')}</div>`}
function gradesView(){return `<div class="view-toolbar"><div><h2 class="view-title">Оценки</h2><p class="card-subtitle">${grades.length} оценок · средний балл ${(grades.reduce((sum,g)=>sum+Number(g.value),0)/Math.max(grades.length,1)).toFixed(1).replace('.',',')}</p></div><button class="primary-button" data-action="grade">＋ Добавить оценку</button></div><section class="card"><table class="table"><thead><tr><th>Предмет</th><th>Тип</th><th>Дата</th><th>Оценка</th><th></th></tr></thead><tbody>${grades.map((g,i)=>`<tr><td>${g.subject}</td><td>${g.type}</td><td>${g.date}</td><td><span class="grade-pill">${g.value}</span></td><td><button class="item-action" data-edit-grade="${i}">Изменить</button> <button class="item-action danger-action" data-delete-grade="${i}">Удалить</button></td></tr>`).join('')}</tbody></table></section>`}
function debtsView(){return `<div class="view-toolbar"><div><h2 class="view-title">Учебные долги</h2><p class="card-subtitle">${debts.length} записи требуют внимания</p></div><button class="primary-button" data-action="debt">＋ Добавить долг</button></div><section class="card"><div class="debt-list">${debts.map((d,i)=>`<div class="task-row"><span class="tag ${d.status==='Срочно'?'danger':'warn'}">${d.status}</span><div class="item-main"><div class="task-name">${d.subject}</div><div class="task-meta"><span>${d.reason}</span><span>Пересдача: ${d.due}</span></div></div><div class="item-actions"><button class="item-action" data-edit-debt="${i}">Изменить</button><button class="item-action danger-action" data-delete-debt="${i}">Удалить</button></div></div>`).join('')}</div></section>`}
function quickAction(type){if(type==='task'){const title=prompt('Название задания');if(title){tasks.push({title,subject:prompt('Предмет')||'Общее',due:prompt('Срок сдачи')||'Без срока',priority:prompt('Приоритет: Высокий или Средний')||'Средний',done:false});save();render();toast('Задание добавлено')}}else if(type==='grade'){const subject=prompt('Предмет');if(subject){grades.push({subject,type:prompt('Тип оценки')||'Другое',date:prompt('Дата')||new Date().toLocaleDateString('ru-RU'),value:Number(prompt('Оценка 2–5')||5)});saveGrades();render();toast('Оценка добавлена')}}else{const subject=prompt('Предмет');if(subject){debts.push({subject,reason:prompt('Причина задолженности')||'Не указано',due:prompt('Дедлайн пересдачи')||'Не указан',status:prompt('Статус: Срочно или В работе')||'В работе'});saveDebts();render();toast('Долг добавлен')}}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.editTask){const i=Number(b.dataset.editTask);tasks[i].title=prompt('Название задания',tasks[i].title)||tasks[i].title;save();render()}if(b.dataset.deleteTask&&confirm('Удалить это задание?')){tasks.splice(Number(b.dataset.deleteTask),1);save();render()}if(b.dataset.editGrade){const i=Number(b.dataset.editGrade);grades[i].subject=prompt('Предмет',grades[i].subject)||grades[i].subject;grades[i].value=Number(prompt('Оценка 2–5',grades[i].value)||grades[i].value);saveGrades();render()}if(b.dataset.deleteGrade&&confirm('Удалить эту оценку?')){grades.splice(Number(b.dataset.deleteGrade),1);saveGrades();render()}if(b.dataset.editDebt){const i=Number(b.dataset.editDebt);debts[i].reason=prompt('Причина задолженности',debts[i].reason)||debts[i].reason;debts[i].due=prompt('Дедлайн пересдачи',debts[i].due)||debts[i].due;saveDebts();render()}if(b.dataset.deleteDebt&&confirm('Удалить этот долг?')){debts.splice(Number(b.dataset.deleteDebt),1);saveDebts();render()}});
function syncProfileUi(){const profile=profiles[activeProfile];document.getElementById('profileName').textContent=profile.name;document.getElementById('profileGroup').textContent=profile.group;document.getElementById('profileAvatar').textContent=profile.name==='Игнатий'?'И':'ВП';document.getElementById('profileSelect').value=activeProfile;document.getElementById('pageTitle').textContent=view==='dashboard'?`Доброе утро, ${profile.name}`:({schedule:'Расписание',calendar:'Календарь',tasks:'Задания',grades:'Оценки',debts:'Учебные долги'}[view]);const scheduleSubtitle=[...document.querySelectorAll('.card-subtitle')].find(el=>el.textContent.includes('Группа'));if(scheduleSubtitle)scheduleSubtitle.textContent=`Группа ${profile.group} · осенний семестр 2026–2027`}
document.getElementById('mobileProfileSwitch').addEventListener('click',()=>document.getElementById('mobileProfileMenu').classList.toggle('open'));document.querySelectorAll('#mobileProfileMenu [data-profile]').forEach(b=>b.addEventListener('click',()=>document.getElementById('mobileProfileMenu').classList.remove('open')));
function lessonMarkup(items,compact=false,week=null){items=items||[];const visible=week?items.filter(x=>!x.room||!/^(I|II) ·/.test(x.room)||x.room.startsWith(`${week} ·`)):items;if(!visible.length)return '<div class="empty">Занятий нет — можно добавить личное событие</div>';const groups=[];visible.forEach(item=>{let group=groups.find(x=>x.time===item.time);if(!group){group={time:item.time,items:[]};groups.push(group)}group.items.push(item)});const roomOf=x=>x.room?x.room.replace(/^(I|II) ·\s*/,''):'';const labelOf=x=>x.slot||((x.room||'').match(/^(I|II) ·/)||[])[1]||'';return `<div class="lesson-list">${groups.map(group=>{const multi=group.items.length>1;return `<div class="${compact?'lesson':'schedule-entry'}"><div class="${compact?'lesson-time':'schedule-time'}">${group.time}</div><div>${group.items.map(x=>`<div class="lesson-part">${multi||labelOf(x)?`<span class="lesson-week">${labelOf(x)}</span>`:''}<div class="${compact?'lesson-name':'schedule-name'}">${x.name}</div><div class="${compact?'lesson-meta':'schedule-detail'}">${x.detail}</div>${multi&&roomOf(x)?`<div class="lesson-room">${roomOf(x)}</div>`:''}</div>`).join('')}</div>${!multi&&roomOf(group.items[0])?`<div class="lesson-room">${roomOf(group.items[0])}</div>`:''}</div>`}).join('')}</div>`}
